import { StyleSheet, Platform } from "react-native";

export const registerStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAF9F6",
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  formContainer: {
    width: "100%",
    maxWidth: 400,
    alignItems: "center",
  },
  icon: {
    marginBottom: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#1B1212",
    marginBottom: 32,
  },
  input: {
    width: "80%",
    borderWidth: 2,
    borderColor: "#1B1212",
    borderRadius: 12,
    padding: 10,
    paddingHorizontal: 16,
    marginBottom: 16,
    fontSize: 16,
    fontWeight: "600",
    color: "#1B1212",
    backgroundColor: "#FFFFFF",
  },
  inputError: {
    borderColor: "#FF6B6B",
    backgroundColor: "#FFF5F5",
  },
  passwordRequirements: {
    width: "80%",
    backgroundColor: "#FFF5F5",
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: "#FF6B6B",
  },
  passwordRequirementsTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#FF6B6B",
    marginBottom: 8,
  },
  passwordRequirementItem: {
    fontSize: 12,
    color: "#FF6B6B",
    marginBottom: 2,
  },
  passwordStrengthContainer: {
    width: "80%",
    marginBottom: 16,
    alignItems: "center",
  },
  passwordStrengthBar: {
    width: "100%",
    height: 6,
    backgroundColor: "#E0E0E0",
    borderRadius: 3,
    marginBottom: 4,
  },
  passwordStrengthFill: {
    height: "100%",
    borderRadius: 3,
  },
  passwordStrengthText: {
    fontSize: 12,
    textAlign: "center",
    fontWeight: "600",
  },
  termsContainer: {
    width: "80%",
    marginBottom: 20,
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: "#1B1212",
    borderRadius: 4,
    marginRight: 10,
    marginTop: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxChecked: {
    backgroundColor: "#5CA377",
    borderColor: "#5CA377",
  },
  checkmark: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "bold",
  },
  checkboxText: {
    flex: 1,
    fontSize: 14,
    color: "#1B1212",
    lineHeight: 20,
  },
  linkText: {
    color: "#5CA377",
    fontWeight: "bold",
    textDecorationLine: "underline",
  },
  button: {
    width: "80%",
    backgroundColor: "#5CA377",
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#1B1212",
    alignItems: "center",
    marginBottom: 16,
    minHeight: 48,
    justifyContent: "center",
  },
  buttonDisabled: {
    backgroundColor: "#A9A9A9",
    borderColor: "#696969",
    opacity: 0.7,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  googleButton: {
    width: "80%",
    backgroundColor: "#FFFFFF",
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#1B1212",
    alignItems: "center",
    marginBottom: 16,
    minHeight: 48,
    justifyContent: "center",
  },
  googleButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1B1212",
  },
  githubButton: {
    width: "80%",
    backgroundColor: "#24292E",
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#1B1212",
    alignItems: "center",
    marginBottom: 16,
    minHeight: 48,
    justifyContent: "center",
  },
  githubButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  oauthButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  oauthLogo: {
    marginRight: 10,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "#FAF9F6",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
    backgroundColor: "#FFFFFF",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#1B1212",
  },
  closeButton: {
    padding: 5,
  },
  closeButtonText: {
    fontSize: 24,
    color: "#1B1212",
    fontWeight: "bold",
  },
  modalContent: {
    flex: 1,
    padding: 20,
    backgroundColor: "#FAF9F6",
  },
  modalCloseButton: {
    marginHorizontal: 20,
    marginBottom: Platform.OS === "ios" ? 30 : 20,
    backgroundColor: "#5CA377",
    padding: 15,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#1B1212",
    alignItems: "center",
  },
  modalCloseButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  passwordContainer: {
    width: "80%",
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#1B1212",
    borderRadius: 12,
    marginBottom: 16,
    backgroundColor: "#FFFFFF",
    position: "relative",
  },
  passwordInput: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    paddingRight: 50,
    fontSize: 16,
    fontWeight: "600",
    color: "#1B1212",
    borderWidth: 0,
  },
  eyeIcon: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: 50,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
  },
  passwordMismatchContainer: {
    width: "80%",
    backgroundColor: "#FFF5F5",
    borderRadius: 8,
    padding: 8,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: "#FF6B6B",
  },
  passwordMismatchText: {
    fontSize: 14,
    color: "#FF6B6B",
    fontWeight: "600",
  },
  passwordMatchContainer: {
    width: "80%",
    backgroundColor: "#F0F9F4",
    borderRadius: 8,
    padding: 8,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: "#5CA377",
  },
  passwordMatchText: {
    fontSize: 14,
    color: "#5CA377",
    fontWeight: "600",
  },
  errorText: {
    color: "#e74c3c",
    fontSize: 12,
    marginTop: 4,
    fontWeight: "500",
  },
});

export const loginStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAF9F6",
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  formContainer: {
    width: "100%",
    maxWidth: 400,
    alignItems: "center",
  },
  icon: {
    marginBottom: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#1B1212",
    marginBottom: 32,
  },
  input: {
    width: "80%",
    borderWidth: 2,
    borderColor: "#1B1212",
    borderRadius: 12,
    padding: 10,
    paddingHorizontal: 16,
    marginBottom: 16,
    fontSize: 16,
    fontWeight: "600",
    color: "#1B1212",
    backgroundColor: "#FFFFFF",
  },
  button: {
    width: "80%",
    backgroundColor: "#5CA377",
    padding: 12,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#1B1212",
    alignItems: "center",
    marginBottom: 16,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  googleButton: {
    width: "80%",
    backgroundColor: "#FFFFFF",
    padding: 12,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#1B1212",
    alignItems: "center",
    marginBottom: 16,
  },
  googleButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1B1212",
  },
  githubButton: {
    width: "80%",
    backgroundColor: "#24292E",
    padding: 12,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#1B1212",
    alignItems: "center",
    marginBottom: 16,
  },
  githubButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  oauthButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  oauthLogo: {
    marginRight: 10,
  },
  disabledButton: {
    opacity: 0.6,
  },
  forgotPasswordLink: {
    marginBottom: 8,
  },
  forgotPasswordLinkText: {
    fontSize: 14,
    color: "#5CA377",
    fontWeight: "600",
    textDecorationLine: "underline",
  },
  forgotPasswordContainer: {
    width: "100%",
    maxWidth: 420,
    alignItems: "center",
  },
  forgotPasswordHeader: {
    alignItems: "center",
    marginBottom: 32,
  },
  forgotPasswordIcon: {
    marginBottom: 16,
  },
  forgotPasswordTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#1B1212",
    marginBottom: 8,
    textAlign: "center",
  },
  forgotPasswordSubtitle: {
    fontSize: 16,
    color: "#666666",
    textAlign: "center",
    lineHeight: 22,
  },
  forgotPasswordCard: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 24,
    marginBottom: 20,
    borderWidth: 2,
    borderColor: "rgba(27, 18, 18, 0.1)",
    shadowColor: "rgba(0, 0, 0, 0.1)",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 5,
  },
  forgotPasswordText: {
    fontSize: 16,
    color: "#1B1212",
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 22,
    fontWeight: "500",
  },
  inputContainer: {
    marginBottom: 20,
  },
  forgotPasswordInput: {
    width: "100%",
    borderWidth: 2,
    borderColor: "#1B1212",
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    fontWeight: "600",
    color: "#1B1212",
    backgroundColor: "#FAF9F6",
  },
  successMessageContainer: {
    backgroundColor: "rgba(92, 163, 119, 0.1)",
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    borderLeftWidth: 4,
    borderLeftColor: "#5CA377",
  },
  successMessageText: {
    fontSize: 16,
    color: "#5CA377",
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 4,
  },
  successMessageSubtext: {
    fontSize: 14,
    color: "#666666",
    textAlign: "center",
    fontStyle: "italic",
  },
  forgotPasswordButton: {
    width: "100%",
    backgroundColor: "#5CA377",
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#1B1212",
    alignItems: "center",
    marginBottom: 12,
  },
  forgotPasswordButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  loadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  cooldownContainer: {
    alignItems: "center",
  },
  progressBarContainer: {
    width: "100%",
    height: 4,
    backgroundColor: "rgba(27, 18, 18, 0.1)",
    borderRadius: 2,
    overflow: "hidden",
  },
  progressBar: {
    height: "100%",
    backgroundColor: "#5CA377",
    borderRadius: 2,
  },
  instructionsCard: {
    width: "100%",
    backgroundColor: "rgba(59, 130, 246, 0.05)",
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "rgba(59, 130, 246, 0.1)",
  },
  instructionsTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1B1212",
    marginBottom: 16,
    textAlign: "center",
  },
  instructionsList: {
    gap: 8,
  },
  instructionItem: {
    fontSize: 14,
    color: "#666666",
    lineHeight: 20,
    fontWeight: "500",
  },
  backToLoginButton: {
    padding: 12,
  },
  backToLoginText: {
    fontSize: 16,
    color: "#5CA377",
    fontWeight: "700",
    textAlign: "center",
  },
  inputError: {
    borderColor: "#e74c3c",
    backgroundColor: "rgba(231, 76, 60, 0.05)",
  },
  errorText: {
    color: "#e74c3c",
    fontSize: 12,
    marginTop: 4,
    fontWeight: "500",
  },
  expiryText: {
    fontSize: 12,
    color: "#f39c12",
    textAlign: "center",
    marginTop: 4,
    fontWeight: "600",
  },
  supportContainer: {
    marginTop: 16,
    padding: 12,
    backgroundColor: "rgba(92, 163, 119, 0.05)",
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#5CA377",
  },
  supportText: {
    fontSize: 13,
    color: "#5CA377",
    textAlign: "center",
    fontWeight: "500",
    fontStyle: "italic",
  },
  errorContainer: {
    width: "80%",
    backgroundColor: "#FFF5F5",
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    borderLeftWidth: 4,
    borderLeftColor: "#FF6B6B",
  },
  errorMessageText: {
    fontSize: 14,
    color: "#FF6B6B",
    fontWeight: "600",
    textAlign: "center",
  },
  passwordContainer: {
    width: "80%",
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#1B1212",
    borderRadius: 12,
    marginBottom: 16,
    backgroundColor: "#FFFFFF",
    position: "relative",
  },
  passwordInput: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    paddingRight: 50,
    fontSize: 16,
    fontWeight: "600",
    color: "#1B1212",
    borderWidth: 0,
    minWidth: 0,
  },
  eyeIcon: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: 50,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
  },
});

export const logoutStyles = StyleSheet.create({
  logoutButton: {
    backgroundColor: "#F87A53",
    padding: 14,
    borderRadius: 12,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    width: "100%",
    marginTop: 8,
    marginBottom: 8,
    shadowColor: "rgba(0, 0, 0, 0.1)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  logoutButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
});