import { StyleSheet } from "react-native";

export const THEME = {
  primary: "#5CA377",
  secondary: "#4299E1",
  danger: "#F87A53",
  warning: "#FFA500",
  background: "#FAF9F6",
  cardBackground: "#FFFFFF",
  text: "#1B1212",
  textLight: "#666666",
  border: "rgba(27, 18, 18, 0.1)",
  shadow: "rgba(0, 0, 0, 0.1)",
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
  },
  loadingText: {
    fontSize: 16,
    color: THEME.textLight,
    textAlign: "center",
    marginVertical: 20,
  },
  recalibrateButton: {
    backgroundColor: THEME.primary,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderWidth: 2,
    borderColor: THEME.text,
    alignItems: "center",
    marginVertical: 8,
  },
  calibrationContainer: {
    alignItems: "center",
  },
  stepsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 16,
    gap: 8,
  },
  stepButton: {
    flex: 1,
    backgroundColor: THEME.secondary,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderWidth: 2,
    borderColor: THEME.text,
    alignItems: "center",
    position: "relative",
  },
  completedStepButton: {
    backgroundColor: THEME.primary,
  },
  buttonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#FFFFFF",
    textAlign: "center",
  },
  completedText: {
    position: "absolute",
    top: -8,
    right: -8,
    backgroundColor: THEME.primary,
    color: "#FFFFFF",
    borderRadius: 10,
    width: 20,
    height: 20,
    textAlign: "center",
    lineHeight: 20,
    fontSize: 12,
    fontWeight: "bold",
  },
  instructionText: {
    fontSize: 14,
    color: THEME.text,
    textAlign: "center",
    marginBottom: 16,
    lineHeight: 20,
  },
  toggleLogButton: {
    backgroundColor: THEME.cardBackground,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: THEME.border,
    marginVertical: 8,
  },
  toggleLogText: {
    fontSize: 14,
    color: THEME.secondary,
    textAlign: "center",
    fontWeight: "600",
  },

  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: THEME.cardBackground,
    borderRadius: 16,
    width: "100%",
    maxWidth: 500,
    maxHeight: "90%",
    borderWidth: 2,
    borderColor: THEME.text,
  },
  scrollContent: {
    padding: 24,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: THEME.text,
  },
  closeButton: {
    fontSize: 32,
    color: THEME.textLight,
    fontWeight: "bold",
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  stepIconContainer: {
    alignItems: "center",
    marginBottom: 20,
  },
  stepIcon: {
    width: 64,
    height: 64,
  },
  instructions: {
    fontSize: 16,
    color: THEME.text,
    lineHeight: 24,
    textAlign: "center",
    marginBottom: 24,
  },
  startButton: {
    backgroundColor: THEME.primary,
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderWidth: 2,
    borderColor: THEME.text,
    alignItems: "center",
    marginBottom: 20,
  },
  startButtonText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  doneButton: {
    backgroundColor: THEME.primary,
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderWidth: 2,
    borderColor: THEME.text,
    alignItems: "center",
    marginBottom: 20,
  },
  countdownContainer: {
    alignItems: "center",
    marginBottom: 20,
  },
  countdownText: {
    fontSize: 18,
    fontWeight: "bold",
    color: THEME.text,
    marginBottom: 12,
    textAlign: "center",
  },
  progressBar: {
    width: "100%",
    height: 8,
    backgroundColor: THEME.border,
    borderRadius: 4,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: THEME.primary,
    borderRadius: 4,
  },
  processingContainer: {
    alignItems: "center",
    marginBottom: 20,
  },
  processingText: {
    fontSize: 16,
    color: THEME.text,
    marginBottom: 16,
    textAlign: "center",
  },
  spinner: {
    width: 32,
    height: 32,
    borderWidth: 3,
    borderColor: THEME.border,
    borderTopColor: THEME.primary,
    borderRadius: 16,
    // Note: CSS animation would be added via stylesheet in web environment
  },
  stepIndicator: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    gap: 8,
  },
  stepDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: THEME.border,
  },
  activeStepDot: {
    backgroundColor: THEME.primary,
  },
  currentStepDot: {
    backgroundColor: THEME.secondary,
    transform: [{ scale: 1.2 }],
  },
});
